# Generated by Django 2.2.1 on 2019-05-25 09:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=200)),
                ('date_of_starting', models.DateField(default=django.utils.timezone.now)),
                ('date_of_ending', models.DateField(default=django.utils.timezone.now)),
                ('no_of_questions', models.IntegerField()),
                ('duration', models.IntegerField(default=180)),
                ('time_of_starting', models.TimeField(default=datetime.datetime(2019, 5, 25, 16, 4, 28, 855633))),
                ('time_of_ending', models.TimeField(default=datetime.datetime(2019, 5, 25, 19, 4, 28, 855633))),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=200)),
                ('a', models.CharField(max_length=200)),
                ('b', models.CharField(max_length=200)),
                ('c', models.CharField(max_length=200)),
                ('d', models.CharField(max_length=200)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.quiz')),
            ],
        ),
    ]
